### ISSUE TITLE
campo ativo retornando false para todos os membros

### ISSUE THREAD

**Issue by danielfireman** [dadosjusbr/parser-cnj#3]
Resultados baseados na coleta TJRJ, mês 03/2018

**Comment by marcos-inja** [comment]
Não entendi muito bem a issue, para mim, está retornando todos como **true**:

![image](https://user-images.githubusercontent.com/76446913/135621799-253f77d1-f8fd-4a07-b239-e36ef477000f.png)

Percebi que tem valores sendo retornados como negativos, acho que é essa linha abaixo que faz isso:

https://github.com/dadosjusbr/coletor-cnj/blob/620b0e034ca6ccb77a2a1d7e28ab3e29fcbff679/src/parser_cnj.py#L120

Não entendi muito bem o proposito dela.
@danielfireman

**Comment by danielfireman** [comment]
Esquisito. Tudo bem, então!
